#!/bin/sh
# Gradle start up script for POSIX generated by BuildAI placeholder
# The real gradlew is fetched by 'gradle wrapper' during CI bootstrap.
echo "Downloading Gradle 8.7..."
curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o /tmp/gradle.zip
unzip -q -o /tmp/gradle.zip -d /tmp
/tmp/gradle-8.7/bin/gradle "$@"
