package com.buildai.ctoai;

import android.os.Bundle;
import android.text.TextUtils;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;
import java.util.List;

/**
 * الدردشة — generated by BuildAI 🤖
 */
public class MainActivity extends AppCompatActivity {

    private final List<String> items = new ArrayList<>();
    private ItemsAdapter adapter;
    private TextView counterText;

    // ✓ تحليل المنتجات
    // ✓ اقتراح معمارية
    // ✓ تقييم المخاطر
    // ✓ نصائح قيادية

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        counterText = findViewById(R.id.counterText);
        EditText inputField = findViewById(R.id.inputField);
        View addButton = findViewById(R.id.addButton);
        RecyclerView list = findViewById(R.id.itemsList);

        adapter = new ItemsAdapter();
        list.setLayoutManager(new LinearLayoutManager(this));
        list.setAdapter(adapter);

        seedItems();

        addButton.setOnClickListener(v -> {
            String text = inputField.getText().toString().trim();
            if (TextUtils.isEmpty(text)) {
                Toast.makeText(this, "اكتب شي أولاً 🙂", Toast.LENGTH_SHORT).show();
                return;
            }
            items.add(0, text);
            adapter.notifyItemInserted(0);
            list.scrollToPosition(0);
            inputField.setText("");
            updateCounter();
        });
    }

    private void seedItems() {
        for (int i = 1; i <= 3; i++) {
            items.add("عنصر تجريبي " + i);
        }
        adapter.notifyDataSetChanged();
        updateCounter();
    }

    private void updateCounter() {
        counterText.setText(String.valueOf(items.size()));
    }

    private void removeItem(int position) {
        if (position >= 0 && position < items.size()) {
            items.remove(position);
            adapter.notifyItemRemoved(position);
            updateCounter();
        }
    }

    private class ItemsAdapter extends RecyclerView.Adapter<ItemsAdapter.Holder> {

        @NonNull
        @Override
        public Holder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
            View view = LayoutInflater.from(parent.getContext())
                    .inflate(R.layout.item_row, parent, false);
            return new Holder(view);
        }

        @Override
        public void onBindViewHolder(@NonNull Holder holder, int position) {
            holder.itemText.setText(items.get(position));
            holder.deleteBtn.setOnClickListener(v -> removeItem(holder.getBindingAdapterPosition()));
        }

        @Override
        public int getItemCount() {
            return items.size();
        }

        class Holder extends RecyclerView.ViewHolder {
            TextView itemText;
            TextView deleteBtn;

            Holder(View itemView) {
                super(itemView);
                itemText = itemView.findViewById(R.id.itemText);
                deleteBtn = itemView.findViewById(R.id.deleteBtn);
            }
        }
    }
}
